[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "1536ba1ce0d50fa9dba6825bff7d630b94ed79a8"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "e990c932e1492f0c0077c6cbdfede6baa0e5a3886ccc36a7eb4e82ff485fe988"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "91d1a7ab2e1d0d1357f3c142ec233f454ec2ae43"
os = "macos"

    [[FreeType2.download]]
    sha256 = "4cef6e3a6b864992fd6ba233fe587f81969af698922ecc26abcefa0d8747d8cc"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-apple-darwin14.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "01903cd7447fb73e88d3eb580ed63819ae5f68af"
os = "windows"

    [[FreeType2.download]]
    sha256 = "eba62d1acb8d193c7742abb25d197f24770fdf63df6e1e5ece6721640a46a855"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "2dfa6c5cf60f9ff54a39cc332b49a41758979942"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "1fde50a38edadccb3f96c1d89c28705d02386cf3840fa4115e70835cdca70528"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "6d16a0958f2fd7667232e132ebe2bb47db0f0fff"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "79c7efca5787d2c0aef2473e84d141b21064f2bfb8dad5101cc47c1cd97bc5c4"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-musl.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "4ee9aba391c00fb24768b4db8e36e51a86d38414"
os = "windows"

    [[FreeType2.download]]
    sha256 = "af9eb159b497b3cc160a0fb4e90d536565ab33ab8b844d17eda522a707f0d00c"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "powerpc64le"
git-tree-sha1 = "81d9452ca92df9fb6fe3ecb84f73f8173ac0ce15"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "57c144e92a4dfb587679dc04e587e15814fd8eb52c6d3d0ea4b58b8472985300"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.powerpc64le-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "e8fe001a808ebd1bf099c8f960e761bf1f3685da"
os = "freebsd"

    [[FreeType2.download]]
    sha256 = "7617e22f8af95a3182e04472ad6f6c336cf34901d72f72aa061914b796b3b06c"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "226b2c4a753aa7aebaf326db945b70d0253f5aec"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "06e7f9039154ddab28beadf0dd271649c70d09039664d64ea2ad67d470c2c862"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "7173a5d6d96a25f6f1fe17287b00626982415606"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "8f18b259fc39ca2ab56ee6dd5689ca9214d53689905b68ca6bc1854572a29f2f"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-musl.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "240520876250f166ec65de82cc04ba12a9793467"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "8b1c9af45f16eff4940be0ece0ab62b9c0955ff254d8780ebaf88861ae640371"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "27ed464bd2554e9d28cf01cfcfefae9767cf68a5"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "ec6d18fe36d0a1bbdf5f2162b4d65d3dfd2d6e4455d23f9c372b430d6d218631"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-musl.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "50a91a2ec0fb97384f329634cb9641dbe1dec338"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "e62c6f0c64b9eae212004a8d792c7ddcffb3e3a679d56521308cac31b97fe600"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-gnueabihf.tar.gz"
