[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "d2b90a0294a1143f146719cc42ac119e4b19c48f"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "44c897059f50be9e4215d4b17730d3a40cd047d5187d40f76a89f3c33a6a51c2"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "ef4f28468070bfa7c599a70b595f08851c53d8df"
os = "macos"

    [[FreeType2.download]]
    sha256 = "33dbf9e6e6419c4fee7ffcb6587ef0dcf6237790aeece80df2f6fc372c25ef4d"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-apple-darwin14.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "76f224ed28150573cde8d60d28f58e06a7a5e519"
os = "windows"

    [[FreeType2.download]]
    sha256 = "a3349e86ef6e7637bfbb3b4bff07e9ac15beb521023fe78c17158ccedfc0be4f"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "e55df83ba1511e7063118240defd92c150ac0c08"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "5b8e6f8206d7b1fed6f2a1b0b2460a9f154271958fc2fd9e39f30c64473b0ec6"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "0a00461856dc1d2bf7d3beb832bcb53e6ed2144b"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "73dbf23506fee0fcb8c0ba2bee612954673993a97aed4060cfd443c89bb42b60"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-musl.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "7c525d9a54ac063fbfe71cb10fbd8905caf9ff94"
os = "windows"

    [[FreeType2.download]]
    sha256 = "c8db61f1627c21bd0316220b191bbbf55d587f23e85fdcb3b14a76d496fff234"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "powerpc64le"
git-tree-sha1 = "10fffa9679d85707d4c40ff8c20efe003eba68ad"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "494c48d550b8840b775d354a322501bacfe51c7ca7848de8f7875d41f0bf0220"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.powerpc64le-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "b670077d32dee7c398442eb6205d5af8b3e26d48"
os = "freebsd"

    [[FreeType2.download]]
    sha256 = "98aa9da5693694e04ac8f525f39aaae8a49c704084dc7bc63e9b15587d429fbf"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "2d6079267625fed2ef45800dc616243c8f325ed3"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "534bcb0ec11de3b68dbda6a6dfe54631a0848bb2d1b1705e5c759ba0ebd20aac"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "54895e4286902418af8ce5ea8eb1ddf56be4e7f1"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "3ca2d9fb8029bdd356766fb59a6b57b807f6d2e02ee01932e8d0fb642cbb98e4"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-musl.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "0b34ecf3ec5c2fe897fd9c3a6dcaf7cf767319eb"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "83c90064a8f73b0a06d25dc8f5a5c4872d314b61d16d0917a4b1c4e6f1e64e62"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "26965512b717cd92e01db337a25bba4319262cdf"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "42c6eb975594f73e89130d8a3edcf8b00ee91fbd6e6e6f942d730e1c417712da"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-musl.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "02cbf0822ddee8b9a0e3a59ff89dd9079adb43db"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "7c35c95542a50065c67254354143a59adb8c9dd1b30ce2bdc4b1272046e832b5"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-gnueabihf.tar.gz"
