[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "5d5c41e59fd77132a20184a3c49a8e9c4f88e230"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "42c7acdddbb6bb819c3b0aaea118bc14c98d179ebdd3f07e2627221d80ea7ca1"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "542bf389e27571285606aa4bf048b2977fa1b71d"
os = "macos"

    [[FreeType2.download]]
    sha256 = "678e70e1817a6ca47fc0ec7ecfd66e09b6abf710b6433f506097d15bb2b8a2f1"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-apple-darwin14.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "8d9f9416072deb7236f8aa05c39f768e058b1e9b"
os = "windows"

    [[FreeType2.download]]
    sha256 = "73d6925858c9d98a46496ab7ccd9019d984a3421954e320638f846194ca985b4"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "994f5ddb71e93db14cc0835fae5b3056b98a95ce"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "f0383ab3114f256318f0f727d7ef3c6d6631151c241df4ad724efa6971fc97a1"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "30e1a49e63c4f13a122e33057aa30c50e5f0e720"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "8f4f861a94d166482a10f38694f27e92a2b540e80bc5812164c9f6c8f3eb3ee5"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-musl.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "dfd778c56eae1e79cd9705c931ea9bd609cdc805"
os = "windows"

    [[FreeType2.download]]
    sha256 = "2eb06833388c55758aa5e2a0820ace3ec7c39b10bd7718b557363bfec1d4343c"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "powerpc64le"
git-tree-sha1 = "099b07a904952f3c853bb72c1fa436cc1e929142"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "4ceba49c7e597c02fccf264c07acbc3a3b1d2fdbe0a4fd9022eb11ead901f49e"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.powerpc64le-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "464e8a23d4f5067d04890e099fd6c65a9b3f3c7c"
os = "freebsd"

    [[FreeType2.download]]
    sha256 = "3c9c32a2490046ebf6119a25a08723af3e04f5d0f7c7f34f08a557ad36636fff"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "3b20f95b26599b9ebd1c4279fba47ab40c9b600e"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "8f9ee30f31823c4682d8adbd2490663eba0386cff7b0b465cd6c419347a349b9"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "a4f2a1bf9cdca065f360bdd58e7fd6d2cfdb6c2b"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "424185ebf34bf2d3c97d14f60b83cf1161afd09dd23e03dc175a36f631b8903d"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-musl.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "4bf36d55cb73aa6d17767d825c727edd406c99f5"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "4e3454e2e1c091f7aef77701590db24387acc0a0eb31dcb8d6e4274d464d0b87"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "720df93093e6600fe062b70c323007988c7ee088"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "3eccbd8388b7cd2e8da7f78d1bc36de4cd228f6caa04a695892f9ac369d6d587"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-musl.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "4e682df12334a55aba3d23c064cc2af531794f19"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "49a744939bda27b4a8b222ae894aa0ed5c8cc619a09c7cd078d2b4f7686fe9ca"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-gnueabihf.tar.gz"
