[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "03d4e4a9b697186ac20706f0d152c377b36949df"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "e0d9e714b128dba6fe7a2cf089d39c98bdfddb8276f49ad47c116fdbc2e91e73"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "15250e33f2e8c8cb4ff92d44ec26666ae223cfba"
os = "macos"

    [[FreeType2.download]]
    sha256 = "1fc4d57f89a7c5c537a9bc25b0460450ab7e1ed241582cf983efedb0eb4437a6"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-apple-darwin14.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "386640526496ebf67209cb68700c80ea4ab3ac76"
os = "windows"

    [[FreeType2.download]]
    sha256 = "1a40da97168a034e527135f4530b36450425a818fa63b8a8d26d0b186bec5e29"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "6f87d29623085e101c2529979e368a6450310c81"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "83e1ee4b03a7fe38c1f85ed35760329772803e0b9f232d80b034b658933c51ac"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "c3e02c47ab675a7558d9f821fceb272ef2f57846"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "cb0b0f8786faa220356193bd7b74e44d307c3c839e86c04ccc4be78e63c27a79"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-musl.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "bbc4799921de714f509433831ab6b311a2d3c671"
os = "windows"

    [[FreeType2.download]]
    sha256 = "a41787608d0d9d01283dc63f5d736086712d7bff1c76b2daebf3e325ebe2265f"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "powerpc64le"
git-tree-sha1 = "6f423ab79b2df75a1e2177d3b76094f8937d2ea6"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "7d9c3b020b3b4f64a195032f3b03b3ae738efb616845d4d5ccdb4693c71f63d1"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.powerpc64le-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "a29e733b3625a244e5c7a6ecfcc786826d29667a"
os = "freebsd"

    [[FreeType2.download]]
    sha256 = "462969c8b61b445c77937c8e89109770cc74c933d310f4543cec660b16406818"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "7d61624d1a52608aaae1e2f3403383aad35454aa"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "aadb5e8ca0fb748819cb7bfb24711a12966a38bbe5bf316cb0c33535419705da"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "4f37c29c8a3d42bbdee7e115ee4dfd1b37395bae"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "443aba9e197addef6f893b01188af5c78386e5c4e2a1a2bfbbb488283d5ad33e"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-musl.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "4f7bb785e6bdde2bae765a10e6ba6119af38b504"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "6fc1f8852994e193a047013f286b1637d87affbe0b147c044209631e89e4f530"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "dff8ce9feaef62f908712d9b5a3c900cc9d188cf"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "eb39995c2f113440131b71aa22e58116471c37e910f1bcc08671ffedfefbf55c"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-musl.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "28bb28fce622cc2dfffd64c20e164ac3ecd187d0"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "b3250ddeffcc85933ec99c0aa3f31a02cb4e0b4b3a4e1bc1747981da0fed198b"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-gnueabihf.tar.gz"
