[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "2f78a2921745fe20254e987d8b669f957ebc655d"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "e454b622558bce8ead9b183d7e6c38ff6ce0b11821332172a61593997a698914"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "1cba9d2cab781044f5f4f6a63178cff3ad39d72d"
os = "macos"

    [[FreeType2.download]]
    sha256 = "a16cfeb588d00f4b33bd2342265327f68b3c6db190a6016ae64f71f3e1240902"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-apple-darwin14.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "eab3554a0049d0bf961d71869a5da14510b7c9d8"
os = "windows"

    [[FreeType2.download]]
    sha256 = "8fb8eb91a5682e020bb8ab22e73f25fba889a381fbf0e5c0fb0e26bd73f6276f"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "f948f5b2da392d2c5751856e49c3afb9a9fdc6f2"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "89811be77346fd8ff074452fddb055cf8f7eb29110c4e134a74dd81dc00eeb91"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "4b93cd46ef66ed4acbd031bf695be15bd6b994c3"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "fe5d90561765d251634cc5229d191e90062e19258e42c20e3940d63630b13e8c"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-musl.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "819adc1e3748854e1d58bf17789f5959c0c674e1"
os = "windows"

    [[FreeType2.download]]
    sha256 = "45f426829a8618d152b93eb7533de01d98537b710bd618b473f1482f23e27915"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "powerpc64le"
git-tree-sha1 = "2f9b181a9b1f11e5f9b9ef78a3c4a253c997df0b"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "1e4d5e10b0560866a2139b1c8f06a3726a311c99642797323a793db70ddaea12"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.powerpc64le-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "cecbf0ffe7ebc7620eeb61da3285834ecaf78d11"
os = "freebsd"

    [[FreeType2.download]]
    sha256 = "2e5999fa6fe0e59b2cd29c6b6b7b2b9a2cbb1b69db4c926e057b7005a2d9adab"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-unknown-freebsd11.1.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "dc520e990dd562d0c489fd7d0764192760ba1b8f"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "668348f3c9270932d20f27c332c1e900a2a30346a6496a0a3277ef1505ea3a3c"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "166bd9c12dc433f4e4a89be0e3acd13f538ba9ba"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "abc5645036d152e68ee7db406ae15620493bede3b43bd49f97a29b099daa58d5"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.aarch64-linux-musl.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "cbf703e1376b93c6289aeb4f945902ae25a084bd"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "2693c1e5ea741bfdec30acfdb999103f3451f1621a2f93c993a0d95587510d55"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.i686-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "212ae38223940482434cb4c14e4c97f09d1cd963"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "b34d6e9a8feec42641b2e5b6be3548a06504777a3c51f562e2f89b0984a95e30"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.x86_64-linux-musl.tar.gz"
[[FreeType2]]
arch = "armv7l"
git-tree-sha1 = "0774a90c93628b568dbd067d8e274340a67e234e"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "9ce112894406be0cf35d70fb0efa000658d237c28aac7b94b33dcb92447a9dac"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.10.1+1/FreeType2.v2.10.1.arm-linux-gnueabihf.tar.gz"
