[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "f755d1efad0bd58f9ad8d1df62671fb9bc4aabac"
os = "macos"

    [[FreeType2.download]]
    sha256 = "4e86036794c5fedb46ffb1d1ede6cc121705b2eee1eab0fca3e938131d387c5e"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.aarch64-apple-darwin.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "c0acc0bc440d04a0ec4958f56cd5560b99c540b7"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "acf30453a6dc30fcac0dd8870034d3880717b2a3832b35312f1fbb537af642a8"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.aarch64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "aarch64"
git-tree-sha1 = "e99fb4832c21048172b9f5621f56d6edfa3bfb20"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "167515af15a8f2588e5e568b57cb0cb77b5ff6c7ce70578a2e73481677c83433"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.aarch64-linux-musl.tar.gz"
[[FreeType2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "92aa2aec7bb151b90593652a17e63d8a5aa0ead5"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "300a6efcb8a28e878ec09f489e7f6117f34d27c75e907679afd3ba199263fed6"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.armv6l-linux-gnueabihf.tar.gz"
[[FreeType2]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "8579380715fb111b406734e6ed00e4567b2f65dc"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "3f68a393ec0e7f376982acb6a3c4c6e5cb420eab757aae0562fac0f017a6b6f7"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.armv6l-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "056c164197f046048d7bdb09b6c2687117756bac"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "79e70cf42997c2628b955d5d8de4a80de4e7c58714b87752127442f63586f818"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.armv7l-linux-gnueabihf.tar.gz"
[[FreeType2]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4187e7066f60fd0f4eb9396bd0d675c30acefe74"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "02fcc3c6f09e4e7cd106bba0fca7584fac441348df55a8d8616af3d2fe972c65"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.armv7l-linux-musleabihf.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "41b7c9435368a7f39f9f3a7a17d4ad2e27c07c26"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "b411689c124522176b92d5fcd4ecf6cd4b47d39fdb9d290c6c8e92260b91b610"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.i686-linux-gnu.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "e15abb240441a652bc174a235a57cb828bd7495a"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "0972c691ec5a949d8d4d1333f1081d25b2cd6954449340568c3aaad4224dcb77"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.i686-linux-musl.tar.gz"
[[FreeType2]]
arch = "i686"
git-tree-sha1 = "cf7511b73dafba3540d315ad080646fa71083380"
os = "windows"

    [[FreeType2.download]]
    sha256 = "11f7c99ab0f3a257c3c8ef589b54d27978f84dbb2ac23e2a72285340bd4e5923"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.i686-w64-mingw32.tar.gz"
[[FreeType2]]
arch = "powerpc64le"
git-tree-sha1 = "1f5a409143dfc8b95fd161f0e71ea61d9abe49db"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "f6b95dfaf96d03f767bc2ac07fab79821efb65418b438bd6170b533b2fa04093"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.powerpc64le-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "a858467f649ba75855819f80fa0c668dce157bf8"
os = "macos"

    [[FreeType2.download]]
    sha256 = "e4b0673d5e1a8bb025646fe41430d0d2aadaf80c7103b7a9c5491f7ac3f8b404"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.x86_64-apple-darwin.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "4fff8dd69d1996234cc96473780198ebc7b3809c"
libc = "glibc"
os = "linux"

    [[FreeType2.download]]
    sha256 = "b4ff8f733e4d4fc61f2d32147a5691c5b394b899398ebb0dd375ae8caeb0d0b7"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.x86_64-linux-gnu.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "b53f05b910a25dc167faf1eda3ff4254d595bc4a"
libc = "musl"
os = "linux"

    [[FreeType2.download]]
    sha256 = "0ca6d79f978dc6bac30f2cd3d4dbb90698467bb23f0a511d20ea82dcb32470a2"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.x86_64-linux-musl.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "ce9ecc22b48f5833c1b89a75263d1d57ab64585a"
os = "freebsd"

    [[FreeType2.download]]
    sha256 = "d22e0c1f2907d8ac7d58dff54589a06919c36971952df8f2ac2409892e3720c9"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.x86_64-unknown-freebsd.tar.gz"
[[FreeType2]]
arch = "x86_64"
git-tree-sha1 = "78180dab4f341f5f0cba74255c7b433af038e47d"
os = "windows"

    [[FreeType2.download]]
    sha256 = "edfa18f4d2f78889156044ebf7f70079f6dc01e2f146dc0d4d93e331de1669a3"
    url = "https://github.com/JuliaBinaryWrappers/FreeType2_jll.jl/releases/download/FreeType2-v2.13.1+0/FreeType2.v2.13.1.x86_64-w64-mingw32.tar.gz"
